### ISSUE TITLE
I am not able to find relevance of this categories thing !

### ISSUE THREAD

**Issue by Harshpreet-hostinko** [Hostinko/Off16#1]
Check the image out , i am not able to get the relevance of this thing , i will prefer to remove it !
![received_1484427838241797](https://cloud.githubusercontent.com/assets/24453940/21011788/e941baba-bd78-11e6-80bf-5c7f21d55b44.jpeg)

**Comment by Dakshster** [comment]
Hello Harsh, 
Thanks for letting us know about this issue.
We've noted the issue. We'll be fixing this issue ASAP.

Best,
Daksh
--
Managing Director,
Hostinko

**Comment by animeshsinghweb** [comment]
Yeah please don't close before fixing, thanks.

**Comment by Dakshster** [comment]
****
