### ISSUE TITLE
Top Level Menu Not Working Properly in WHMCS

### ISSUE THREAD

**Issue by Harshpreet-hostinko** [Hostinko/Off16#2]
When we are on the WHMCS version of the website and are trying to go back to homepage of the website , either of the menu elements named as "Home" either don't work or take them to the WHMCS home . I would request you guys to check that out and redirect all buttons that have matching elements on home page to the home page . For e.g Home - Home , Contact Us to main website contact us by daksh etc etc .

**Comment by animeshsinghweb** [comment]
Ok, I would see to it.

**Comment by Dakshster** [comment]
I've Fixed that Bug.
