### ISSUE TITLE
Mobile Optimisation

### ISSUE THREAD

**Issue by Harshpreet-hostinko** [Hostinko/Off16#3]
Still the mobile website of hostinko in the WHMCS part is not mobile optimized, and page width needs to be managed pls look into it.

**Comment by animeshsinghweb** [comment]
Can you provide te screenshot of the bug for clear inspection?
Thanks.

**Comment by Harshpreet-hostinko** [comment]
Yupp wait !

**Comment by animeshsinghweb** [comment]
Is it sorted?
